[package]
name = "deepphonemizer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = {version = "0.14.0", features = ["download-libtorch"]}
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.27"
itertools = "0.8"
